title: Amirhossein Mahdinejad
logo: /assets/photo/Amirhossein-Mahdinejad.png
description: Cloud Developer | Computer Programming Instructor
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal